// src/data/casos.ts
// Para agregar un nuevo caso: añadir un objeto al array `casos`.
// El slug se convierte automáticamente en URL: /casos/{slug}

export interface CaseStudy {
  slug:     string;
  num:      string;
  brand:    string;
  category: { es: string; en: string };
  tagline:  { es: string; en: string };
  desc:     { es: string; en: string };
  liveUrl:  string;
  liveDomain: string;
  image:    string;
  metrics:  Array<{ val: string; label: { es: string; en: string } }>;
  challenge: { es: string; en: string };
  solutionPoints: Array<{ es: string; en: string }>;
  stack:    string[];
  results:  Array<{
    val:   string;
    label: { es: string; en: string };
    desc:  { es: string; en: string };
  }>;
  // Nota de contexto temporal sobre los resultados (punto de partida + plazo medido)
  resultsNote?: { es: string; en: string };
  // SEO — title/description con métricas (fallback a category/desc si se omiten)
  seoTitle?: { es: string; en: string };
  seoDesc?:  { es: string; en: string };
  // Schema Article — entidad "about" + fechas de publicación
  about?:    { name: string; description: string; url: string };
  datePublished?: string;
  dateModified?:  string;
  // CTA de cierre conectado directamente al reto del caso (fórmula "¿Tienes X?")
  cta?: {
    eyebrow: { es: string; en: string };
    title:   { es: string; en: string };
    sub:     { es: string; en: string };
  };
}

export const casos: CaseStudy[] = [
  {
    slug:  'el-zarco',
    num:   '01',
    brand: 'El Zarco',
    category: {
      es: 'Arquitectura B2B',
      en: 'B2B Architecture',
    },
    tagline: {
      es: 'De 6 horas de gestión manual a cero intervención humana.',
      en: 'From 6 hours of manual coordination to zero human intervention.',
    },
    desc: {
      es: 'Transformamos una operación mayorista 100% manual en infraestructura digital B2B con precios dinámicos, portal cerrado y automatización completa de pedidos.',
      en: 'We transformed a 100% manual wholesale operation into a B2B digital infrastructure with dynamic pricing, closed portal, and full order automation.',
    },
    liveUrl:    'https://elzarcodistribuidora.com.mx',
    liveDomain: 'elzarcodistribuidora.com.mx',
    image: '/imgs/el-zarco.svg',
    metrics: [
      { val: '+25%', label: { es: 'Aumento AOV',        en: 'AOV Uplift' } },
      { val: '100%', label: { es: 'Sync Automatizada',  en: 'Automated Sync' } },
      { val: '−67%', label: { es: 'Tiempo de proceso',  en: 'Processing Time' } },
      { val: '8',    label: { es: 'APIs conectadas',     en: 'APIs Connected' } },
    ],
    challenge: {
      es: 'Distribuidora mayorista con más de 150 clientes activos operando completamente en hojas de cálculo, llamadas telefónicas y WhatsApp. Sin catálogo digital, sin precios diferenciados por cliente y sin visibilidad de inventario en tiempo real. El equipo de ventas perdía más de 6 horas diarias en coordinación manual — pedidos sin trazabilidad, precios en la cabeza del vendedor y facturas generadas a mano. Equivalente a tener 1.5 personas dedicadas exclusivamente a tareas que hoy el sistema ejecuta solo.',
      en: 'Wholesale distributor with 150+ active clients operating entirely on spreadsheets, phone calls, and WhatsApp. No digital catalog, no customer-specific pricing, and no real-time inventory visibility. The sales team lost 6+ hours daily to manual coordination — untraceable orders, pricing in the salesperson\'s head, and invoices generated by hand. Equivalent to having 1.5 people dedicated solely to tasks the system now runs on its own.',
    },
    solutionPoints: [
      { es: 'Portal B2B cerrado con acceso por invitación — cada cliente ve solo sus precios y catálogo', en: 'Closed B2B portal with invitation-only access — each client sees only their pricing and catalog' },
      { es: 'Precios dinámicos por tier: mayoreo, menudeo y VIP, sincronizados en tiempo real',           en: 'Dynamic tiered pricing: wholesale, retail, and VIP, synced in real time' },
      { es: 'Catálogo digital con disponibilidad de inventario conectado al sistema interno',             en: 'Digital catalog with inventory availability connected to the internal system' },
      { es: 'Automatización completa via Make: de orden a factura PDF sin intervención humana',          en: 'Full automation via Make: from order to PDF invoice with zero human intervention' },
      { es: 'Dashboard de ventas en Airtable con métricas en tiempo real para el equipo',                en: 'Sales dashboard in Airtable with real-time metrics for the team' },
      { es: 'Flujos Klaviyo para reabastecimiento y seguimiento postventa automatizado',                 en: 'Klaviyo flows for automated restocking and post-sale follow-up' },
    ],
    stack: ['Shopify Plus', 'Airtable', 'Make', 'Klaviyo', 'Custom API', 'Liquid'],
    resultsNote: {
      es: 'Resultados medidos a 90 días del lanzamiento del portal.',
      en: 'Results measured 90 days after the portal launch.',
    },
    results: [
      {
        val: '+25%',
        label: { es: 'Aumento en AOV',        en: 'AOV Increase' },
        desc:  { es: 'Incremento en valor promedio de pedido gracias al upsell estructurado en el portal — los distribuidores ven sugerencias de producto complementario en el flujo de orden, sin intervención del equipo de ventas.', en: 'Increase in average order value driven by structured upsell in the portal — distributors see complementary product suggestions inside the order flow, with no intervention from the sales team.' },
      },
      {
        val: '100%',
        label: { es: 'Pedidos automatizados', en: 'Orders Automated' },
        desc:  { es: 'De orden a factura PDF sin intervención manual del equipo de ventas.', en: 'From order to PDF invoice with no manual intervention from the sales team.' },
      },
      {
        val: '−67%',
        label: { es: 'Tiempo de proceso',     en: 'Processing Time' },
        desc:  { es: 'El tiempo de procesamiento pasó de 6 horas a menos de 2 horas diarias — y ese tiempo lo consume el sistema, no el equipo. El equipo de ventas usa ese tiempo en atención de nuevos clientes.', en: 'Processing time dropped from 6 hours to under 2 hours a day — and that time is spent by the system, not the team. The sales team now uses it to onboard new clients.' },
      },
    ],
    seoTitle: {
      es: 'El Zarco: Portal B2B en Shopify Plus — +25% AOV, −67% tiempo de proceso | Flouvia CDMX',
      en: 'El Zarco: B2B Portal on Shopify Plus — +25% AOV, −67% process time | Flouvia',
    },
    seoDesc: {
      es: 'Caso de estudio: digitalizamos la operación mayorista de El Zarco — portal B2B cerrado en Shopify Plus, precios dinámicos y automatización completa de pedidos. Resultado en 90 días: −67% tiempo de proceso, +25% AOV, 100% pedidos sin intervención manual.',
      en: 'Case study: we digitized El Zarco\'s wholesale operation — closed B2B portal on Shopify Plus, dynamic pricing and full order automation. In 90 days: −67% process time, +25% AOV, 100% orders with no manual intervention.',
    },
    about: {
      name: 'El Zarco',
      description: 'Distribuidora mayorista con más de 150 clientes activos en CDMX',
      url: 'https://elzarcodistribuidora.com.mx',
    },
    datePublished: '2025-03-01',
    dateModified:  '2026-05-29',
    cta: {
      eyebrow: { es: '¿TIENES UN RETO SIMILAR?', en: 'HAVE A SIMILAR CHALLENGE?' },
      title:   { es: 'Construimos lo mismo para tu operación.', en: 'We build the same for your operation.' },
      sub:     { es: 'Si tu equipo gestiona pedidos, inventario o clientes de forma manual, podemos automatizarlo. Comienza con un diagnóstico sin costo.', en: 'If your team manages orders, inventory or clients by hand, we can automate it. Start with a free diagnosis.' },
    },
  },

  {
    slug:  'setnpet',
    num:   '02',
    brand: 'Setnpet',
    category: {
      es: 'CRO & E-commerce',
      en: 'CRO & E-commerce',
    },
    tagline: {
      es: 'De 0.9% a 1.3% de conversión en 90 días — sin cambiar el tráfico.',
      en: 'From 0.9% to 1.3% conversion in 90 days — without changing traffic.',
    },
    desc: {
      es: 'Convertimos una tienda con tráfico orgánico sólido y conversión baja en un sistema de crecimiento sostenible con retención activa, flujos de Klaviyo y arquitectura de conversión custom.',
      en: 'We turned a store with solid organic traffic and low conversion into a sustainable growth system with active retention, Klaviyo flows, and custom conversion architecture.',
    },
    liveUrl:    'https://setnpet.com',
    liveDomain: 'setnpet.com',
    image: '/imgs/set-n-pet.svg',
    metrics: [
      { val: '+42%', label: { es: 'Tasa de conversión', en: 'Conversion Rate' } },
      { val: '3×',   label: { es: 'Retención LTV',       en: 'LTV Retention' } },
      { val: '−18%', label: { es: 'Abandono de carrito', en: 'Cart Abandonment' } },
      { val: '5',    label: { es: 'Flujos Klaviyo',       en: 'Klaviyo Flows' } },
    ],
    challenge: {
      es: 'Marca D2C de productos para mascotas con tráfico orgánico sólido pero tasa de conversión de 0.9%. Sin sistema de retención activo, 68% de abandono en carrito y un tema Shopify genérico que no comunicaba el posicionamiento de marca. El 90% de las ventas venían de clientes nuevos — sin recurrencia, sin LTV, sin sistema. Cada peso de adquisición compraba una sola compra: el CAC crecía sin una retención que lo compensara.',
      en: 'D2C pet products brand with solid organic traffic but a 0.9% conversion rate. No active retention system, 68% cart abandonment, and a generic Shopify theme that failed to communicate brand positioning. 90% of sales came from new customers — no recurrence, no LTV, no system. Every acquisition peso bought a single purchase: CAC kept rising with no retention to offset it.',
    },
    solutionPoints: [
      { es: 'Auditoría CRO completa: mapas de calor, análisis de sesión y funnel granular por dispositivo', en: 'Full CRO audit: heatmaps, session analysis, and device-level granular funnel breakdown' },
      { es: 'Tema Shopify custom — cada módulo diseñado para maximizar conversión',                         en: 'Custom Shopify theme — every module engineered to maximize conversion' },
      { es: '5 flujos Klaviyo: bienvenida, carrito abandonado, winback, post-compra y browse abandonment', en: '5 Klaviyo flows: welcome, abandoned cart, winback, post-purchase, and browse abandonment' },
      { es: 'A/B testing framework con 8 variantes activas y análisis estadístico de resultados',          en: 'A/B testing framework with 8 active variants and statistical result analysis' },
      { es: 'Programa de puntos integrado para incentivar compra recurrente y reducir CAC',                en: 'Integrated loyalty program to incentivize repeat purchases and reduce CAC' },
      { es: 'GA4 + Meta Pixel con data layer custom para atribución precisa multi-canal',                  en: 'GA4 + Meta Pixel with custom data layer for precise multi-channel attribution' },
    ],
    stack: ['Shopify', 'Klaviyo', 'Hotjar', 'Custom Liquid', 'Google Analytics 4', 'Meta Pixel'],
    resultsNote: {
      es: 'Resultados medidos a 90 días del lanzamiento. Punto de partida: 0.9% de conversión, 68% de abandono de carrito.',
      en: 'Results measured 90 days after launch. Starting point: 0.9% conversion, 68% cart abandonment.',
    },
    results: [
      {
        val: '+42%',
        label: { es: 'Tasa de conversión', en: 'Conversion Rate' },
        desc:  { es: 'La tasa de conversión pasó de 0.9% a 1.3% global — sin aumentar el presupuesto de tráfico. El cambio fue en la arquitectura del flujo de compra, no en la inversión en adquisición.', en: 'Conversion rate went from 0.9% to 1.3% overall — without raising the traffic budget. The change was in the purchase-flow architecture, not in acquisition spend.' },
      },
      {
        val: '3×',
        label: { es: 'Retención LTV',      en: 'LTV Retention' },
        desc:  { es: 'El 90% de las ventas venían de clientes nuevos antes de los flujos Klaviyo. A 90 días del lanzamiento, los clientes recurrentes representan 3× más revenue que al inicio — reduciendo el CAC efectivo sin tocar la inversión en ads.', en: '90% of sales came from new customers before the Klaviyo flows. 90 days after launch, recurring customers represent 3× more revenue than at the start — lowering effective CAC without touching ad spend.' },
      },
      {
        val: '−18%',
        label: { es: 'Abandono de carrito', en: 'Cart Abandonment' },
        desc:  { es: 'Reducción en tasa de abandono tras optimizar el checkout y activar los flujos de recuperación.', en: 'Reduction in cart abandonment after optimizing checkout and activating recovery flows.' },
      },
    ],
    seoTitle: {
      es: 'Setnpet: CRO en Shopify — +42% conversión, 3× retención LTV | Flouvia',
      en: 'Setnpet: CRO on Shopify — +42% conversion, 3× LTV retention | Flouvia',
    },
    seoDesc: {
      es: 'Caso de estudio CRO: pasamos a Setnpet de 0.9% a 1.3% de conversión global en 90 días sin aumentar el tráfico — tema Shopify custom, 5 flujos Klaviyo y arquitectura de conversión. 3× retención LTV, −18% abandono de carrito.',
      en: 'CRO case study: we took Setnpet from 0.9% to 1.3% overall conversion in 90 days without adding traffic — custom Shopify theme, 5 Klaviyo flows and conversion architecture. 3× LTV retention, −18% cart abandonment.',
    },
    about: {
      name: 'Setnpet',
      description: 'Marca D2C de productos para mascotas con tráfico orgánico sólido',
      url: 'https://setnpet.com',
    },
    datePublished: '2025-01-15',
    dateModified:  '2026-05-29',
    cta: {
      eyebrow: { es: '¿TIENES TRÁFICO PERO LA CONVERSIÓN NO SUBE?', en: 'TRAFFIC, BUT CONVERSION WON\'T MOVE?' },
      title:   { es: 'Así se ve el mismo reto resuelto.', en: 'This is that same challenge, solved.' },
      sub:     { es: 'Si tienes visitas pero las ventas no crecen al mismo ritmo, auditamos tu embudo y te mostramos exactamente dónde se pierden.', en: 'If you have visits but sales aren\'t growing at the same pace, we audit your funnel and show you exactly where they\'re lost.' },
    },
  },
];
