// src/data/casos.ts
// Para agregar un nuevo caso: añadir un objeto al array `casos`.
// El slug se convierte automáticamente en URL: /casos/{slug}

export interface CaseStudy {
  slug:     string;
  num:      string;
  brand:    string;
  category: { es: string; en: string };
  tagline:  { es: string; en: string };
  desc:     { es: string; en: string };
  liveUrl:  string;
  liveDomain: string;
  image:    string;
  metrics:  Array<{ val: string; label: { es: string; en: string } }>;
  challenge: { es: string; en: string };
  solutionPoints: Array<{ es: string; en: string }>;
  stack:    string[];
  results:  Array<{
    val:   string;
    label: { es: string; en: string };
    desc:  { es: string; en: string };
  }>;
}

export const casos: CaseStudy[] = [
  {
    slug:  'el-zarco',
    num:   '01',
    brand: 'El Zarco',
    category: {
      es: 'Arquitectura B2B',
      en: 'B2B Architecture',
    },
    tagline: {
      es: 'Digitalización mayorista a escala total.',
      en: 'Full-scale wholesale digitization.',
    },
    desc: {
      es: 'Transformamos una operación mayorista 100% manual en infraestructura digital B2B con precios dinámicos, portal cerrado y automatización completa de pedidos.',
      en: 'We transformed a 100% manual wholesale operation into a B2B digital infrastructure with dynamic pricing, closed portal, and full order automation.',
    },
    liveUrl:    'https://elzarcodistribuidora.com.mx',
    liveDomain: 'elzarcodistribuidora.com.mx',
    image: '/imgs/el-zarco.svg',
    metrics: [
      { val: '+25%', label: { es: 'Aumento AOV',        en: 'AOV Uplift' } },
      { val: '100%', label: { es: 'Sync Automatizada',  en: 'Automated Sync' } },
      { val: '−67%', label: { es: 'Tiempo de proceso',  en: 'Processing Time' } },
      { val: '8',    label: { es: 'APIs conectadas',     en: 'APIs Connected' } },
    ],
    challenge: {
      es: 'Distribuidora mayorista con más de 150 clientes activos operando completamente en hojas de cálculo, llamadas telefónicas y WhatsApp. Sin catálogo digital, sin precios diferenciados por cliente y sin visibilidad de inventario en tiempo real. El equipo de ventas perdía más de 6 horas diarias en coordinación manual — pedidos sin trazabilidad, precios en la cabeza del vendedor y facturas generadas a mano.',
      en: 'Wholesale distributor with 150+ active clients operating entirely on spreadsheets, phone calls, and WhatsApp. No digital catalog, no customer-specific pricing, and no real-time inventory visibility. The sales team lost 6+ hours daily to manual coordination — untraceable orders, pricing in the salesperson\'s head, and invoices generated by hand.',
    },
    solutionPoints: [
      { es: 'Portal B2B cerrado con acceso por invitación — cada cliente ve solo sus precios y catálogo', en: 'Closed B2B portal with invitation-only access — each client sees only their pricing and catalog' },
      { es: 'Precios dinámicos por tier: mayoreo, menudeo y VIP, sincronizados en tiempo real',           en: 'Dynamic tiered pricing: wholesale, retail, and VIP, synced in real time' },
      { es: 'Catálogo digital con disponibilidad de inventario conectado al sistema interno',             en: 'Digital catalog with inventory availability connected to the internal system' },
      { es: 'Automatización completa via Make: de orden a factura PDF sin intervención humana',          en: 'Full automation via Make: from order to PDF invoice with zero human intervention' },
      { es: 'Dashboard de ventas en Airtable con métricas en tiempo real para el equipo',                en: 'Sales dashboard in Airtable with real-time metrics for the team' },
      { es: 'Flujos Klaviyo para reabastecimiento y seguimiento postventa automatizado',                 en: 'Klaviyo flows for automated restocking and post-sale follow-up' },
    ],
    stack: ['Shopify Plus', 'Airtable', 'Make', 'Klaviyo', 'Custom API', 'Liquid'],
    results: [
      {
        val: '+25%',
        label: { es: 'Aumento en AOV',        en: 'AOV Increase' },
        desc:  { es: 'Incremento en valor promedio de pedido al implementar upsell estructurado en el portal B2B.', en: 'Increase in average order value from implementing structured upsell in the B2B portal.' },
      },
      {
        val: '100%',
        label: { es: 'Pedidos automatizados', en: 'Orders Automated' },
        desc:  { es: 'De orden a factura PDF sin intervención manual del equipo de ventas.', en: 'From order to PDF invoice with no manual intervention from the sales team.' },
      },
      {
        val: '−67%',
        label: { es: 'Tiempo de proceso',     en: 'Processing Time' },
        desc:  { es: 'Reducción en tiempo de procesamiento de pedidos: de 6 horas a menos de 2.', en: 'Reduction in order processing time: from 6 hours to under 2.' },
      },
    ],
  },

  {
    slug:  'setnpet',
    num:   '02',
    brand: 'Setnpet',
    category: {
      es: 'CRO & E-commerce',
      en: 'CRO & E-commerce',
    },
    tagline: {
      es: 'Sistema D2C de alto crecimiento para mascotas.',
      en: 'High-growth D2C system for pet brands.',
    },
    desc: {
      es: 'Convertimos una tienda con tráfico orgánico sólido y conversión baja en un sistema de crecimiento sostenible con retención activa, flujos de Klaviyo y arquitectura de conversión custom.',
      en: 'We turned a store with solid organic traffic and low conversion into a sustainable growth system with active retention, Klaviyo flows, and custom conversion architecture.',
    },
    liveUrl:    'https://setnpet.com',
    liveDomain: 'setnpet.com',
    image: '/imgs/set-n-pet.svg',
    metrics: [
      { val: '+42%', label: { es: 'Tasa de conversión', en: 'Conversion Rate' } },
      { val: '3×',   label: { es: 'Retención LTV',       en: 'LTV Retention' } },
      { val: '−18%', label: { es: 'Abandono de carrito', en: 'Cart Abandonment' } },
      { val: '5',    label: { es: 'Flujos Klaviyo',       en: 'Klaviyo Flows' } },
    ],
    challenge: {
      es: 'Marca D2C de productos para mascotas con tráfico orgánico sólido pero tasa de conversión de 0.9%. Sin sistema de retención activo, 68% de abandono en carrito y un tema Shopify genérico que no comunicaba el posicionamiento de marca. El 90% de las ventas venían de clientes nuevos — sin recurrencia, sin LTV, sin sistema.',
      en: 'D2C pet products brand with solid organic traffic but a 0.9% conversion rate. No active retention system, 68% cart abandonment, and a generic Shopify theme that failed to communicate brand positioning. 90% of sales came from new customers — no recurrence, no LTV, no system.',
    },
    solutionPoints: [
      { es: 'Auditoría CRO completa: mapas de calor, análisis de sesión y funnel granular por dispositivo', en: 'Full CRO audit: heatmaps, session analysis, and device-level granular funnel breakdown' },
      { es: 'Tema Shopify custom — cada módulo diseñado para maximizar conversión',                         en: 'Custom Shopify theme — every module engineered to maximize conversion' },
      { es: '5 flujos Klaviyo: bienvenida, carrito abandonado, winback, post-compra y browse abandonment', en: '5 Klaviyo flows: welcome, abandoned cart, winback, post-purchase, and browse abandonment' },
      { es: 'A/B testing framework con 8 variantes activas y análisis estadístico de resultados',          en: 'A/B testing framework with 8 active variants and statistical result analysis' },
      { es: 'Programa de puntos integrado para incentivar compra recurrente y reducir CAC',                en: 'Integrated loyalty program to incentivize repeat purchases and reduce CAC' },
      { es: 'GA4 + Meta Pixel con data layer custom para atribución precisa multi-canal',                  en: 'GA4 + Meta Pixel with custom data layer for precise multi-channel attribution' },
    ],
    stack: ['Shopify', 'Klaviyo', 'Hotjar', 'Custom Liquid', 'Google Analytics 4', 'Meta Pixel'],
    results: [
      {
        val: '+42%',
        label: { es: 'Tasa de conversión', en: 'Conversion Rate' },
        desc:  { es: 'Aumento en la tasa de conversión global tras el tema custom y la arquitectura CRO.', en: 'Increase in overall conversion rate after the custom theme and CRO architecture.' },
      },
      {
        val: '3×',
        label: { es: 'Retención LTV',      en: 'LTV Retention' },
        desc:  { es: 'Triple de clientes recurrentes en 90 días desde el lanzamiento de los flujos de retención.', en: 'Triple the recurring customers within 90 days of launching the retention flows.' },
      },
      {
        val: '−18%',
        label: { es: 'Abandono de carrito', en: 'Cart Abandonment' },
        desc:  { es: 'Reducción en tasa de abandono tras optimizar el checkout y activar los flujos de recuperación.', en: 'Reduction in cart abandonment after optimizing checkout and activating recovery flows.' },
      },
    ],
  },
];
